#!/bin/sh

set -e

VERSION=12.0.7

if [ ! -e sphinxEnv ]; then
    curl -L -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-${VERSION}.tar.gz
    tar xvfz virtualenv-${VERSION}.tar.gz
    rm virtualenv-${VERSION}.tar.gz
    python virtualenv-${VERSION}/virtualenv.py sphinxEnv
    ./sphinxEnv/bin/pip install Sphinx==1.3.1
fi
