#!/bin/bash

version=$1

cat > jwrapper-cavm.xml <<-EOF
	<JWrapper>
		
		<!-- The name of the app bundle -->
		<BundleName>UCSC Xena</BundleName>
		
		<!-- The specification for one app within the bundle -->
		<App>
		  <Name>UCSC Xena</Name>
		  <LogoPNG>cavm/sammy-icon.png</LogoPNG>
		  <MainClass>cavm.core</MainClass>
		  <!--
		  <Param>one</Param>
		  <Param>two</Param> -->
		</App>
		
		<SupportedLanguages>en</SupportedLanguages>
		
		<!-- App is a per-user app, it won't elevate and install for all users and the shared config folder will be per-user -->
		<InstallType>CurrentUser</InstallType>
		
		<!-- Splash and Logo -->
		<SplashPNG>cavm/sammy-splash.png</SplashPNG>
		<BundleLogoPNG>cavm/sammy-icon.png</BundleLogoPNG>
		
		<!-- JVM options (e.g. extra memory) -->
		<JvmOptions>
		 <JvmOption>-Xmx4g</JvmOption>
		</JvmOptions>

		<Pack200Effort>5</Pack200Effort>
		<UpdateURL>https://genome-cancer.ucsc.edu/download/public/get-xena</UpdateURL>

		<!-- The JREs JWrapper should use for Windows, Linux32, Linux64... -->
		<Windows32JRE>JRE-1.6/win32/jre1.6.0_16</Windows32JRE>
		<Windows64JRE>JRE-1.6/win32/jre1.6.0_16</Windows64JRE>
		<Linux32JRE>JRE-1.6/linux/jre1.6.0_16</Linux32JRE>
		<Linux64JRE>JRE-1.6/linuxx64/jre1.6.0_16</Linux64JRE>
		<Mac64JRE>JRE-1.7/macos64/jre1.7.0_45.jre</Mac64JRE>
		<Mac32JRE>JRE-1.7/macos64/jre1.7.0_45.jre</Mac32JRE>

		<!-- The files that the app wants to bundle, here we have just one which is a JAR file and we specify that it should be on the launch classpath -->
		<File classpath='yes'>cavm/target/uberjar/cavm-${version}-standalone.jar</File>
		
	</JWrapper>
	EOF

cd ../jwrapper
# create link to project if it doesn't exist, or throw if we can't.
if [ ! -h cavm ]; then
	ln -s ../cavm .
fi
java -Xmx512m -jar jwrapper-00031607960.jar cavm/jwrapper-cavm.xml
